#useing code for create ec2 instance help with cloudFromation pipeline
  
AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 instance with Security Group

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select your VPC

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Deepak-SG

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: linux-cli
      ImageId: ami-073130f74f5ffb161   # Ensure this AMI exists in your region
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: Deepak

